import random as r
gamers = ['Нурхасым', 'Рамазан', 'Расберген', 'Раметулла', 'Расул', 'Куралбек', 'Рашид', 'Рауаж', 'Реймбай', 'Миша', 'Нака', 'Толик']
clubs = ['Barselona','Liverpul', 'Mancity', 'Bavariya', 'Arsenal', 'PSG', 'Real Madrid', 'Atletico', 'Juventus', 'Chelsea', 'Man U', 'Inter'] 

bir = r.choice(gamers)
gamers.remove(bir)
eki = r.choice(gamers)
gamers.remove(eki)
ush = r.choice(gamers)
gamers.remove(ush)
tort = r.choice(gamers)
gamers.remove(tort)
bes = r.choice(gamers)
gamers.remove(bes)
alti = r.choice(gamers)
gamers.remove(alti)
jeti = r.choice(gamers)
gamers.remove(jeti)
segiz = r.choice(gamers)
gamers.remove(segiz)
togiz = r.choice(gamers)
gamers.remove(togiz)
oon = r.choice(gamers)
gamers.remove(oon)
onbir = r.choice(gamers)
gamers.remove(onbir)
oneki = r.choice(gamers)


birr = r.choice(clubs)
print(f"1. {bir} - {birr}")
clubs.remove(birr)
ekii = r.choice(clubs)
print(f"2. {eki} - {ekii}")
clubs.remove(ekii)
ushh = r.choice(clubs)
print(f"3. {ush} - {ushh}")
clubs.remove(ushh)
tortt = r.choice(clubs)
print(f"4. {tort} - {tortt}")
clubs.remove(tortt)
bess = r.choice(clubs)
print(f"5. {bes} - {bess}")
clubs.remove(bess)
altii = r.choice(clubs)
print(f"6. {alti} - {altii}")
clubs.remove(altii)
jetii = r.choice(clubs)
print(f"7. {jeti} - {jetii}")
clubs.remove(jetii)
segizz = r.choice(clubs)
print(f"8. {segiz} - {segizz}")
clubs.remove(segizz)
togizz = r.choice(clubs)
print(f"9. {togiz} - {togizz}")
clubs.remove(togizz)
oonn = r.choice(clubs)
print(f"10. {oon} - {oonn}")
clubs.remove(oonn)
onbirr = r.choice(clubs)
print(f"11. {onbir} - {onbirr}")
clubs.remove(onbirr)
onekii = r.choice(clubs)
print(f"12. {oneki} - {onekii}")
